dct = {'ad_parameters': [{'p': 'remuneration_type',
                    'pl': 'Тип оплаты',
                    'pu': 'rtr',
                    'v': '1',
                    'vl': 'Цена'},
                   {'p': 'type',
                    'pl': 'Тип сделки',
                    'pu': 'typ',
                    'v': 'sell',
                    'vl': 'Продажа'},
                   {'p': 'category',
                    'pl': 'Категория',
                    'pu': 'cat',
                    'v': 2010,
                    'vl': 'Легковые авто'},
                   {'p': 'cars_brand_v2',
                    'pl': 'Марка',
                    'pu': 'cbnd2',
                    'v': 'category_2010.mark_audi',
                    'vl': 'Audi'},
                   {'p': 'cars_model_v2',
                    'pl': 'Модель',
                    'pu': 'cmdl2',
                    'v': 'category_2010.mark_audi.model_80',
                    'vl': '80'},
                   {'p': 'cars_gen_v2',
                    'pl': 'Поколение',
                    'pu': 'cgen2',
                    'v': 'category_2010.mark_audi.model_80.generation_80_iv_b317122',
                    'vl': 'IV (B3)'},
                   {'p': 'regdate',
                    'pl': 'Год',
                    'pu': 'rgd',
                    'v': '1990',
                    'vl': '1990'},
                   {'p': 'mileage',
                    'pl': 'Пробег, км',
                    'pu': 'mlg',
                    'v': 390000,
                    'vl': ''},
                   {'p': 'cars_engine',
                    'pl': 'Тип двигателя',
                    'pu': 'cre',
                    'v': '2',
                    'vl': 'Дизель'},
                   {'p': 'cars_capacity',
                    'pl': 'Объем, л',
                    'pu': 'crca',
                    'v': 8,
                    'vl': '1.6 л'},
                   {'p': 'cars_gearbox',
                    'pl': 'Коробка передач',
                    'pu': 'crg',
                    'v': '2',
                    'vl': 'Механика'},
                   {'p': 'cars_type',
                    'pl': 'Тип кузова',
                    'pu': 'crt',
                    'v': '1',
                    'vl': 'Седан'},
                   {'p': 'cars_drive',
                    'pl': 'Привод',
                    'pu': 'crd',
                    'v': '1',
                    'vl': 'Передний'},
                   {'p': 'cars_color',
                    'pl': 'Цвет',
                    'pu': 'crc',
                    'v': '2',
                    'vl': 'Серый / серебристый'},
                   {'p': 'condition',
                    'pl': 'Состояние',
                    'pu': 'cnd',
                    'v': '1',
                    'vl': 'С пробегом'},
                   {'p': 'cars_alloy_wheels',
                    'pl': 'Легкосплавные диски',
                    'pu': 'caw',
                    'v': True,
                    'vl': 'Да'},
                   {'p': 'region',
                    'pl': 'Область',
                    'pu': 'rgn',
                    'v': 4,
                    'vl': 'Могилевская'},
                   {'p': 'area',
                    'pl': 'Город / Район',
                    'pu': 'ar',
                    'v': '13',
                    'vl': 'Могилев'},
                   {'p': 'delivery_enabled',
                    'pl': 'Товары с Куфар Доставкой',
                    'pu': 'dle',
                    'v': False,
                    'vl': '-'},
                   {'p': 'safedeal_enabled',
                    'pl': 'Товары с Куфар Оплатой',
                    'pu': 'sde',
                    'v': False,
                    'vl': '-'}],
}

print(dct['ad_parameters'][-3]['vl'])